/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tom_ffmpegAPI_Mp4player */

#ifndef _Included_com_tom_ffmpegAPI_Mp4player
#define _Included_com_tom_ffmpegAPI_Mp4player
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tom_ffmpegAPI_Mp4player
 * Method:    playmp4
 * Signature: (Ljava/lang/String;Landroid/view/Surface;Landroid/media/AudioTrack;)V
 */
JNIEXPORT void JNICALL Java_com_tom_ffmpegAPI_Mp4player_playmp4
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_tom_ffmpegAPI_Mp4player
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tom_ffmpegAPI_Mp4player_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
